var exports = {
  "Abbot's Bromley": "ABB",
  "Aboyne Dinnet": "ABD",
  "Abergavenny": "ABE",
  "Aberfeldy": "ABF",
  "Abington": "ABI",
  "Aberfoyle": "ABL",
  "Abingdon Bridge": "ABN",
  "Aboyne": "ABO",
  "Aberchirder": "ABR",
  "Abergavenny SW": "ABS",
  "Aberystwyth Pier": "ABY",
  "Accrington NE": "ACC",
  "Achnasheen": "ACH",
  "Achnabourin": "ACN",
  "Aberdare SE": "ADE",
  "Andoversford": "ADF",
  "Alfriston Bridge": "AFB",
  "Alford": "AFD",
  "Abergele South": "AGS",
  "Altnaharra": "AHA",
  "Aln Bridge": "ALB",
  "Alcester": "ALC",
  "Aylesham": "ALE",
  "Alfreton": "ALF",
  "Allendale Bridge": "ALL",
  "Alnwick Moor SW": "ALM",
  "Alston": "ALO",
  "Alfreton South": "ALS",
  "Alton": "ALT",
  "Alva": "ALV",
  "Alton Southwest": "ALW",
  "Alyth": "ALY",
  "Amberley": "AMB",
  "Ambleside": "AMS",
  "Amulree": "AMU",
  "Andover SW": "AND",
  "Andover SE": "ANE",
  "Ansty Cross": "ANX",
  "Appleby": "APP",
  "Ardvasar": "ARD",
  "Ardrishaig Lighthouse": "ARL",
  "Arundel": "ARU",
  "Ashbury": "ASB",
  "Ashford East": "ASE",
  "Ashbourne": "ASH",
  "Aspatria": "ASP",
  "Ashford South": "ASS",
  "Aston Down": "AST",
  "Airdrie Southwest": "ASW",
  "Ashley": "ASY",
  "Atherstone": "ATH",
  "Attleborough": "ATT",
  "Alton Towers": "ATW",
  "Auldgirth": "AUL",
  "Avebury": "AVE",
  "Axminster": "AXM",
  "Aylesbury": "AYL",
  "Aysgarth": "AYS",
  "Banbury W": "BA1",
  "Banbury N": "BA2",
  "Ballachulish Bridge": "BAB",
  "Backwater Reservoir": "BAC",
  "Badminton": "BAD",
  "Bath East": "BAE",
  "Balfron": "BAF",
  "Bangor-on-Dee": "BAG",
  "Barrhill": "BAH",
  "Bakewell": "BAK",
  "Bala": "BAL",
  "Bampton": "BAM",
  "Banbury": "BAN",
  "Barnard Castle": "BAR",
  "Basingstoke": "BAS",
  "Bath Racecourse SW": "BAT",
  "Banchory West": "BAW",
  "Bracken Bank": "BBK",
  "Bath Bridge": "BBR",
  "Bicester Airfield": "BC1",
  "Bicester NE": "BC2",
  "Bicester N": "BC3",
  "Bishop's Caundle": "BCA",
  "Banchory East": "BCE",
  "Bishop's Cleeve NW": "BCL",
  "Brechin": "BCN",
  "Bishops Castle": "BCS",
  "Bishops Cleeve W": "BCW",
  "Banchory": "BCY",
  "Bidford Finish E": "BD1",
  "Bidford Finish W": "BD2",
  "Bodmin SE": "BDM",
  "Beadnell Harbour": "BDN",
  "Balado": "BDO",
  "Bodelwyddan": "BDW",
  "Bardney": "BDY",
  "Beaminster": "BEA",
  "Bedford Bridge": "BED",
  "Beer Head W": "BEE",
  "Bellingham": "BEL",
  "Bembridge": "BEM",
  "Bentpath": "BEN",
  "Berwick W": "BER",
  "St Bees Head": "BES",
  "Beattock": "BET",
  "Beulah": "BEU",
  "Beverley": "BEV",
  "Bewl Water": "BEW",
  "Booker Finish SW": "BF1",
  "Booker Finish NW": "BF2",
  "Banff": "BFF",
  "Biggar": "BGA",
  "Brigg": "BGG",
  "Bangor SE": "BGO",
  "Blairgowrie": "BGR",
  "Bedlands Gate": "BGT",
  "Basingstoke West": "BGW",
  "Bath North": "BHN",
  "Bicester Rail Bridge": "BIB",
  "Bicester Control Tower": "BIC",
  "Bidford": "BID",
  "Bicester East": "BIE",
  "Broughton-in-Furness": "BIF",
  "Biggleswade": "BIG",
  "Billinghay": "BIL",
  "Biddenden": "BIN",
  "Birdlip": "BIR",
  "Bishop Auckland": "BIS",
  "Brinkley Church": "BKY",
  "Blakehill Farm": "BLA",
  "Blandford": "BLD",
  "Blenheim N": "BLE",
  "Blaenau Ffestiniog": "BLF",
  "Ballinluig": "BLG",
  "Balloch": "BLH",
  "Blidworth": "BLI",
  "Blakeney Point": "BLK",
  "Blanchland": "BLN",
  "Bolsover SW": "BLO",
  "Blair Atholl": "BLR",
  "Barnsley S": "BLS",
  "Barnsley W": "BLW",
  "Bletchley": "BLY",
  "Balmaha": "BMA",
  "Brynamman": "BMM",
  "Braemar East": "BMR",
  "Bingham": "BNG",
  "Brinkworth": "BNK",
  "Ben Nevis": "BNV",
  "Bicester North West": "BNW",
  "Booker SW": "BO1",
  "Booker W": "BO2",
  "Booker NW": "BO3",
  "Turville Windmill": "BO4",
  "Rockwell End": "BO5",
  "Bridge of Avon": "BOA",
  "Booker M40 Bridge": "BOB",
  "Bridge of Cally": "BOC",
  "Bodiam": "BOD",
  "Bridge of Gaur": "BOG",
  "Bootle": "BOL",
  "Bodmin SW": "BOM",
  "Boncath": "BON",
  "Booker Airfield": "BOO",
  "Boroughbridge": "BOR",
  "Boston": "BOS",
  "Bottesford": "BOT",
  "Bourne": "BOU",
  "Bovey Tracey": "BOV",
  "Bourton-on-the-water": "BOW",
  "Bozeat": "BOZ",
  "Barnstaple": "BPL",
  "Bridport": "BPT",
  "Brackley South": "BRC",
  "Bradbury": "BRD",
  "Brecon": "BRE",
  "Bradford-on-avon": "BRF",
  "Brenig": "BRG",
  "Brough": "BRH",
  "Bridgnorth": "BRI",
  "Broad Oak": "BRK",
  "Brill": "BRL",
  "Bromsgrove": "BRM",
  "Burn": "BRN",
  "Broadway": "BRO",
  "Brampton": "BRP",
  "Brora": "BRR",
  "Braemar Stadium": "BRS",
  "Brent Tor": "BRT",
  "Bruton": "BRU",
  "Barrow": "BRW",
  "Bromyard": "BRY",
  "Bury St Edmunds S": "BS1",
  "Bury St Edmunds N": "BS2",
  "Bury St Edmunds": "BSE",
  "Basingstoke N": "BSN",
  "Bunessan Pier": "BSS",
  "Brecon SW": "BSW",
  "Bassenthwaite E": "BT2",
  "Bassenthwaite Lake NW": "BTH",
  "Battle": "BTL",
  "Bridlington": "BTN",
  "Ballater": "BTR",
  "Buttermere": "BTT",
  "Burbage": "BUB",
  "Buckingham": "BUC",
  "Bude": "BUD",
  "Burley Gate": "BUG",
  "Burnhope Reservoir": "BUH",
  "Builth Wells": "BUI",
  "Buckfastleigh": "BUK",
  "Bullington": "BUL",
  "Bungay": "BUN",
  "Burton upon Stather": "BUS",
  "Butser Hill": "BUT",
  "Buxton": "BUX",
  "Beauly": "BUY",
  "Belvoir": "BVR",
  "Bovington": "BVT",
  "Bridgwater E": "BWE",
  "Bwlch": "BWL",
  "Cambridge se": "CAB",
  "Candover Church": "CAC",
  "Callander": "CAD",
  "Canterbury East": "CAE",
  "Castle Howard": "CAH",
  "Cairnwell": "CAI",
  "Calvert Rail Junction": "CAL",
  "Cambridge North": "CAM",
  "Cannock": "CAN",
  "Canonbie": "CAO",
  "Carlton Moor": "CAR",
  "Cambridge South": "CAS",
  "Canterbury": "CAT",
  "Cambridge West": "CAW",
  "Caxton Gibbet": "CAX",
  "Carter Bar": "CBA",
  "Conisbrough Castle": "CBC",
  "Creagan Bridge": "CBG",
  "Carisbrooke Castle": "CBK",
  "Chilbolton": "CBN",
  "Carrbridge": "CBR",
  "Carreg Cennen Castle": "CCC",
  "Castle Carrock Dam NW": "CCK",
  "Crickhowell": "CCL",
  "Clay Cross Reservoir": "CCR",
  "Cadbury Cross": "CCX",
  "Castle Douglas SW": "CDO",
  "Clattershaws Dam S": "CDS",
  "Cerne Abbas": "CER",
  "Cowes": "CES",
  "Chollerford Bridge": "CFB",
  "Crieff": "CFF",
  "Corgarf": "CGF",
  "Croglin": "CGL",
  "Cherington": "CGT",
  "Chard": "CHA",
  "Charlbury": "CHB",
  "Chipping Campden": "CHC",
  "Chesterfield": "CHD",
  "Chedworth": "CHE",
  "Chichester W": "CHI",
  "Chirk": "CHK",
  "Cheltenham": "CHL",
  "Chipping Norton": "CHN",
  "Chorley West": "CHO",
  "Chipping": "CHP",
  "Charterhall Field": "CHR",
  "Chelmsford S": "CHS",
  "Chatteris": "CHT",
  "Church Houses": "CHU",
  "Chieveley": "CHV",
  "Charwelton": "CHW",
  "Cinderford": "CIN",
  "Cirencester Church": "CIR",
  "Chicklade": "CKL",
  "Challock Chalk Pit": "CL2",
  "Challock East": "CL3",
  "Claydon": "CLA",
  "Clacton E": "CLC",
  "Culdrose A/f": "CLD",
  "Clee": "CLE",
  "Clitheroe": "CLI",
  "Challock": "CLK",
  "Carlisle": "CLL",
  "Chilham": "CLM",
  "Calne W": "CLN",
  "Clova": "CLO",
  "Clyffe Pypard": "CLP",
  "Culmstock": "CLS",
  "Corran Lighthouse": "CLT",
  "Clunas": "CLU",
  "Callaly Castle": "CLY",
  "Cheltenham East": "CME",
  "Carmarthen": "CMN",
  "Cockermouth": "CMO",
  "Canterbury North East": "CNE",
  "Connel": "CNL",
  "Corndon Hill": "CNN",
  "Carno": "CNO",
  "Chinnor": "CNR",
  "Cirencester nw": "CNW",
  "Conwy Bridge": "CNY",
  "Charlestown of Aberlour": "COA",
  "Corby South": "COB",
  "Colchester": "COC",
  "Coldstream": "COD",
  "Corwen NE": "COE",
  "Crocketford": "COF",
  "Corby Glen": "COG",
  "Coldingham": "COH",
  "Cocking": "COK",
  "Comrie": "COM",
  "Condover": "CON",
  "Corby": "COR",
  "Cosford Junction": "COS",
  "Colt Crag Reservoir": "COT",
  "Coupar Angus": "COU",
  "Colchester West": "COW",
  "Camphill start/finish south": "CP1",
  "Camphill Chimney": "CP2",
  "Camphill": "CPH",
  "Clapham Reservoir N": "CPN",
  "Chippenham W": "CPW",
  "Cranwell North": "CRA",
  "Cranbrook": "CRB",
  "Crick": "CRC",
  "Cricklade": "CRD",
  "Crediton Station": "CRE",
  "Cerrig": "CRG",
  "Crianlarich": "CRI",
  "Crewkerne": "CRK",
  "Crowland A/f": "CRL",
  "Crinan": "CRN",
  "Crowland Bridge": "CRO",
  "Cromer Pier": "CRP",
  "Carron": "CRR",
  "Crediton West": "CRW",
  "Cray Reservoir": "CRY",
  "Canterbury South East": "CSE",
  "Cosford Airfield": "CSF",
  "Crask Bridge": "CSK",
  "Coniston": "CSN",
  "Cross Hands": "CSS",
  "Colsterworth": "CSW",
  "Crathie Bridge": "CTH",
  "Catterick": "CTK",
  "Charlestown NE": "CTN",
  "Cottam": "CTT",
  "Clunbury Hill": "CU2",
  "Cullompton": "CUL",
  "Clun": "CUN",
  "Cupar": "CUP",
  "Currock Hill": "CUR",
  "Craven Arms": "CVN",
  "Chipping Warden": "CWA",
  "Crewe East": "CWE",
  "Corwen": "CWN",
  "Carsington Water": "CWR",
  "Cwmbran SW": "CWS",
  "Chatsworth": "CWT",
  "Conwy S": "CWY",
  "Dallachy": "DAL",
  "Dalmally": "DAM",
  "Danby": "DAN",
  "Darlington": "DAR",
  "Darwell": "DAW",
  "Dunblane": "DBN",
  "Devil's Bridge": "DBR",
  "Devil's Dyke": "DDK",
  "Deal": "DEA",
  "Deddington": "DED",
  "Denbigh": "DEN",
  "Depden Water Tower": "DEP",
  "Derwent": "DER",
  "Detling": "DET",
  "Devizes": "DEV",
  "Duffield": "DFF",
  "Dalton-in-Furness": "DFU",
  "Didcot": "DID",
  "Dingwall": "DIN",
  "Diss": "DIS",
  "Ditchlingbeacon": "DIT",
  "Dunkeld": "DKD",
  "Dunkery Beacon": "DKY",
  "Dale Bridge": "DLB",
  "Dallas": "DLS",
  "Dalston": "DLT",
  "Dunbar SE": "DNB",
  "Durham Northeast": "DNE",
  "Dunning": "DNG",
  "Dunoon": "DNN",
  "Dunstable Roundabout": "DNS",
  "Duntulm": "DNT",
  "Doncaster Northwest": "DNW",
  "Docking": "DOC",
  "Dolgellau": "DOG",
  "Dollar": "DOL",
  "Dorchester": "DOR",
  "Doune": "DOU",
  "Dover Marina": "DOV",
  "Downham Market": "DOW",
  "Droma Bridge": "DRB",
  "Driffield": "DRI",
  "Darlton": "DRL",
  "Droitwich": "DRO",
  "Denbigh Ridge S": "DRS",
  "Drumshade": "DRU",
  "Daventry SE": "DSE",
  "Dursley SW": "DSW",
  "Donington": "DTN",
  "Duncton": "DUC",
  "Dufftown": "DUF",
  "Dulverton": "DUL",
  "Dumfries": "DUM",
  "Dunstable Airfield": "DUN",
  "Durham": "DUR",
  "Duns": "DUS",
  "Dufton": "DUT",
  "Dursley NW": "DUY",
  "Daventry N": "DVN",
  "Dalwhinnie": "DWI",
  "Danbury N": "DYN",
  "Dyserth": "DYS",
  "Eaglescott": "EAG",
  "Earith": "EAR",
  "Easterton": "EAS",
  "Eastgate": "EAT",
  "Eastwell": "EAW",
  "Edgehill": "EDG",
  "Edzell": "EDZ",
  "Eggesford N": "EGG",
  "Elkstone S": "ELK",
  "Ellesmere": "ELL",
  "Elmswell W": "ELM",
  "Ely": "ELY",
  "Enstone": "ENS",
  "Eastbourne NW": "ENW",
  "Etchingham": "ETC",
  "Etal": "ETL",
  "Ettington": "ETT",
  "Evesham": "EVE",
  "Ennerdale Water W": "EWW",
  "Eyebrook": "EYE",
  "Fakenham": "FAK",
  "Falgunzeon": "FAL",
  "Faringdon": "FAR",
  "Faversham": "FAV",
  "Falkirk West": "FAW",
  "Fraserburgh": "FBG",
  "Feshie Airstrip": "FE1",
  "Feshie Start N": "FE2",
  "Feshie Descent Point": "FE3",
  "Feshie Watersports": "FE4",
  "Feshie S": "FE5",
  "Fearnan": "FEA",
  "Fenny Compton": "FEN",
  "Ferness": "FER",
  "Feshiebridge": "FES",
  "Fettercairn": "FET",
  "Felixstowe Pier": "FEX",
  "Forfar": "FFR",
  "Firle Beacon": "FIB",
  "Filey": "FIL",
  "Finmere": "FIM",
  "Finavon": "FIN",
  "Fishguard": "FIS",
  "Flamborough": "FLA",
  "Four Marks": "FMA",
  "Fort William NE": "FNE",
  "Falmouth NW": "FNW",
  "Fort Augustus": "FOA",
  "Fordoun": "FOD",
  "Folkestone": "FOL",
  "Fordingbridge": "FOR",
  "Foston": "FOS",
  "Fovant": "FOV",
  "Foxton": "FOX",
  "Freuchie": "FRE",
  "Fridaythorpe": "FRI",
  "Frome": "FRO",
  "Framlingham": "FRW",
  "Fort William": "FTW",
  "Feltwell": "FWL",
  "Gainsborough Power Station": "GA2",
  "Galashiels": "GAA",
  "Garboldisham": "GAB",
  "Garforth": "GAF",
  "Gargrave West": "GAG",
  "Gainsborough": "GAI",
  "Gallowfauld": "GAL",
  "Garten": "GAR",
  "Gateshead East": "GAT",
  "Gaydon": "GAY",
  "Gribbin Head": "GBB",
  "Great Bedwyn": "GBE",
  "Glasbury Bridge": "GBR",
  "Glen Dee Bridge": "GDB",
  "Glyndebourne": "GDE",
  "Great Dun Fell": "GDF",
  "Gordon": "GDN",
  "Gretna Services": "GES",
  "Glenfiddich Lodge": "GFD",
  "Glenfarg Reservoir E": "GFG",
  "Glen Falloch": "GFL",
  "Garsdale Head": "GHD",
  "Gillingham": "GIL",
  "Gisburn": "GIS",
  "Glastonbury": "GLA",
  "Gelt Bridge": "GLB",
  "Glendevon": "GLE",
  "Glenforsa": "GLF",
  "Gleneagles": "GLN",
  "Gloucester West": "GLO",
  "Gloucester South": "GLS",
  "Glenlatterach Dam N": "GLT",
  "Gairlochy": "GLY",
  "Grantown NE": "GNE",
  "Grains": "GNS",
  "Goole N": "GO2",
  "Goole NE": "GOO",
  "Goring": "GOR",
  "Gransden NW": "GR1",
  "Gransden SE": "GR2",
  "Gransden W": "GR3",
  "Gransden E": "GR4",
  "Grantham": "GRA",
  "Grasmere Church": "GRC",
  "Great Ashfield": "GRF",
  "Grimwith Reservoir": "GRI",
  "Gransden Lodge": "GRL",
  "Great Malvern": "GRM",
  "Greenlaw": "GRN",
  "Grosmont": "GRO",
  "Grassington": "GRS",
  "Great Rundale Tarn": "GRT",
  "Grafham Water": "GRW",
  "Glassonby": "GSS",
  "Grantown": "GTN",
  "Grantown S": "GTS",
  "Great Witley": "GTW",
  "Guisborough": "GUI",
  "Guisborough SW": "GUW",
  "Garve": "GVE",
  "Goodwood Grandstand": "GWD",
  "Grantown SW": "GWS",
  "Great Yarmouth S": "GYS",
  "Hay Bluff": "HAB",
  "Halesland": "HAD",
  "Halesworth": "HAE",
  "Hailsham": "HAI",
  "Hawick": "HAK",
  "Halton": "HAL",
  "Harrogate North": "HAN",
  "Harting": "HAR",
  "Hastings": "HAS",
  "Hatherleigh": "HAT",
  "Haverhill": "HAV",
  "Hawkhurst": "HAW",
  "Hay-on-wye": "HAY",
  "HB start west": "HB1",
  "HB start north": "HB2",
  "HB start east": "HB3",
  "HB East": "HB4",
  "HB control point east": "HB5",
  "HB control point west": "HB6",
  "Haydon Bridge": "HBR",
  "Herstmonceux": "HCX",
  "Haddington": "HDD",
  "Helmsdale": "HDL",
  "Hardwick": "HDW",
  "Hereford Cathedral": "HEC",
  "Heathfield E": "HEE",
  "Helensburgh": "HEL",
  "Hereford Racecourse": "HER",
  "Henstridge": "HES",
  "Heugh Head": "HEU",
  "Hexham": "HEX",
  "Highham": "HGM",
  "Hembury Hill": "HHL",
  "Hinton Start W": "HI1",
  "Hinckley": "HIC",
  "Hinton in the Hedges": "HIN",
  "Hunstanton Lighthouse": "HLH",
  "Helmsley": "HLM",
  "Hungerford North": "HNN",
  "Huntercombe": "HNT",
  "Honeybourne": "HOB",
  "Holsworthy": "HOL",
  "Horncastle": "HOR",
  "Hesket Old Town": "HOT",
  "Howden Dam": "HOW",
  "Harpley": "HPY",
  "Harrietsham": "HRR",
  "Hartside Top": "HRT",
  "Hawes": "HSE",
  "Hathersage": "HSG",
  "Hornsea Mere": "HSM",
  "Honington Airfield": "HTN",
  "Huntly": "HTY",
  "Humber Bridge": "HUM",
  "Hungerford": "HUN",
  "Hurstbourne Tarrant": "HUR",
  "Husbands Bosworth": "HUS",
  "Havant S": "HVS",
  "Havant NW": "HVT",
  "Haverfordwest": "HVW",
  "Halfway House": "HWH",
  "Haltwistle": "HWL",
  "Hay East": "HYE",
  "Ilsley": "ILS",
  "Insch": "INC",
  "Ingleton": "ING",
  "Inchkinloch": "INK",
  "Inverness": "INS",
  "Inverary": "INV",
  "Ipswich E": "IPE",
  "Inverness SE": "ISE",
  "Islip": "ISL",
  "Invershin": "IVS",
  "Ivybridge East": "IVY",
  "Iwerne Minster": "IWE",
  "Jedburgh": "JED",
  "Kielder Castle": "KCA",
  "Kincraig": "KCG",
  "Kendal": "KDL",
  "Keevil": "KEE",
  "Keswick": "KEK",
  "Kelso": "KEL",
  "Kempock Point": "KEM",
  "Kenley": "KEN",
  "Kettering South": "KES",
  "Kexby Bridge": "KEX",
  "Kingsclere": "KGS",
  "Kinbrace": "KIB",
  "Kinclaven": "KIC",
  "Kidderminster": "KID",
  "Kielder Reservoir": "KIE",
  "Kingussie": "KIG",
  "Kirkharle": "KIK",
  "Kilcreggan": "KIL",
  "Kingham": "KIM",
  "Kineton": "KIN",
  "Kippen": "KIP",
  "Kirton-in-lindsey": "KIR",
  "Kilham": "KLH",
  "Killin": "KLN",
  "Kirkby Lonsdale": "KLO",
  "Kinloss": "KLS",
  "King's Lynn": "KLY",
  "Kentmere": "KME",
  "Kirkmichael": "KML",
  "Kenmore": "KMR",
  "Knaresborough": "KNA",
  "Knighton": "KNI",
  "Knowstone": "KNO",
  "Kirkbymoorside": "KRB",
  "Kirriemuir": "KRM",
  "Kingston Bagpuize": "KSB",
  "Kirkby Stephen Station": "KST",
  "Keith": "KTH",
  "Kilmington": "KTN",
  "Kinlochewe": "KWE",
  "Kibworth": "KWO",
  "Kyleakin": "KYL",
  "Lasham Start Southeast": "LA1",
  "Lasham Start East": "LA2",
  "Lasham Church": "LA3",
  "Lasham Start South": "LA4",
  "Lasham West": "LA5",
  "Lasham Start North": "LA6",
  "Lasham Finish West": "LA7",
  "Lasham Golden Pot": "LA8",
  "Lauder": "LAD",
  "Llanelli East": "LAE",
  "Langport": "LAG",
  "Lairg": "LAI",
  "Lampeter": "LAM",
  "Langham": "LAN",
  "Lapford": "LAP",
  "Lattrig": "LAR",
  "Lasham Clubhouse": "LAS",
  "Latheron": "LAT",
  "Launceston": "LAU",
  "Longbridge Deverill": "LBD",
  "Loch Bradan E": "LBE",
  "Lambourn": "LBN",
  "Laggan Bridge": "LBR",
  "Lochbuie": "LBU",
  "Leighton Buzzard NE": "LBZ",
  "Llyn Celyn NW": "LCE",
  "Lanchester": "LCH",
  "Lower Clopton": "LCL",
  "Lochindorb Castle": "LDB",
  "Laggan Dam": "LDM",
  "Lindores": "LDR",
  "Lochearnhead": "LEA",
  "Ledbury": "LED",
  "Lee-on-solent": "LEE",
  "Leadenham": "LEH",
  "Leicester M1 Services": "LEI",
  "Leck": "LEK",
  "Loch Eil West": "LEL",
  "Leicester North": "LEN",
  "Leominster": "LEO",
  "Loch Errochty East": "LER",
  "Leicester South": "LES",
  "Lewes North": "LEW",
  "Leyburn": "LEY",
  "Leighton Buzzard": "LEZ",
  "Llanfyllin": "LFN",
  "Loch Laggan North East": "LGG",
  "Lochgilphead": "LGI",
  "Loch Garry N": "LGN",
  "Lochgoilhead": "LGO",
  "Liphook": "LIP",
  "Lismore": "LIS",
  "Littleport": "LIT",
  "Liskeard SE": "LKD",
  "Llangollen": "LLA",
  "Llanbadarn": "LLB",
  "Llanfair Caereinion": "LLC",
  "Llandovery": "LLD",
  "Lleweni Parc": "LLE",
  "Llangynidr Bridge": "LLG",
  "Llanidloes": "LLI",
  "Llanrwst": "LLN",
  "Llandeilo": "LLO",
  "Llantysilio": "LLS",
  "Loch Lomond Tarbet": "LLT",
  "Llandrindod Wells": "LLW",
  "Long Marston": "LMA",
  "Lochmaben": "LMB",
  "Loch Mullardoch East": "LMD",
  "Loch Morlich": "LMO",
  "Ledmore": "LMR",
  "Loch Muick": "LMU",
  "Leominster NW": "LMW",
  "Loch Moy": "LMY",
  "Lichfield NE": "LNE",
  "Lochailort": "LOA",
  "Lockerbie": "LOC",
  "Linn of Dee": "LOD",
  "Loch Gairloch SE": "LOG",
  "Loch Kinord": "LOK",
  "Loch Lochy North East": "LOL",
  "Lake of Menteith": "LOM",
  "Longleat": "LON",
  "Loch Quoich East": "LOQ",
  "Louth": "LOU",
  "Lowick": "LOW",
  "Little Rissington": "LRI",
  "Lanark": "LRK",
  "Llandysul": "LSL",
  "Loch Seilich N": "LSN",
  "Liss": "LSS",
  "Long Sutton": "LSU",
  "Lincoln Southwest": "LSW",
  "Langtoft": "LTF",
  "Longtown": "LTN",
  "Ludlow": "LUD",
  "Luncarty": "LUN",
  "Lussa Loch S": "LUS",
  "Lutterworth": "LUT",
  "Loch Venachar": "LVE",
  "Lavenham": "LVN",
  "Low Lorton": "LWL",
  "Lewes nw": "LWN",
  "Leyland North East": "LYD",
  "Lyneham a/f": "LYN",
  "Ladybower Reservoir": "LYR",
  "Lyveden": "LYV",
  "Machynlleth Station": "MAC",
  "Market Deeping": "MAD",
  "Marlborough E": "MAE",
  "Market Harborough": "MAH",
  "Maidstone East": "MAI",
  "Malton": "MAL",
  "Malmesbury": "MAM",
  "Manton": "MAN",
  "Marlborough": "MAR",
  "Masham": "MAS",
  "Matlock": "MAT",
  "Market Weighton": "MAW",
  "Mablethorpe": "MBL",
  "Market Bosworth": "MBO",
  "Montford Bridge": "MBR",
  "Melbury Bubb": "MBU",
  "Manby": "MBY",
  "March": "MCH",
  "Maidstone North": "MDN",
  "Measham": "MEA",
  "East Meon": "MEE",
  "Melksham": "MEL",
  "Membury": "MEM",
  "Mendlesham": "MEN",
  "Mere": "MER",
  "Melton Mowbray": "MET",
  "West Meon Hut": "MEW",
  "Mexborough S": "MEX",
  "Mansfield NE": "MFD",
  "Micheldever": "MIC",
  "Mingary Pier": "MIG",
  "Milfield": "MIL",
  "Midhurst Mast": "MIM",
  "Mintlaw": "MIN",
  "Milnthorpe": "MIT",
  "Midhurst West": "MIW",
  "Mellon Charles": "MLL",
  "Melmerby": "MLM",
  "Molton": "MLN",
  "Milton": "MLT",
  "Maryport NE": "MNE",
  "Menai Strait": "MNS",
  "Millom NW": "MNW",
  "Monkton": "MOK",
  "Monmouth": "MOM",
  "Montgomery": "MON",
  "Muir of Ord": "MOO",
  "Morpeth": "MOP",
  "Moreton-in-marsh": "MOR",
  "Mossat": "MOS",
  "Mortimer Church": "MOT",
  "Moulton Church": "MOU",
  "Moy Lodge": "MOY",
  "Margate E": "MRE",
  "Marham": "MRM",
  "Market Rasen": "MRN",
  "Maryport": "MRY",
  "Mansfield SE": "MSE",
  "Mottisfont Station": "MTF",
  "Moota Hill": "MTH",
  "Melton Mast": "MTM",
  "Montrose": "MTR",
  "Mudford Gate": "MUD",
  "Mumbles Head": "MUM",
  "Mundford": "MUN",
  "Mursley": "MUR",
  "Murton": "MUT",
  "Methven": "MVN",
  "Mallwyd": "MWD",
  "Mynd S": "MY2",
  "Mynd N": "MY3",
  "Mynd": "MYN",
  "Monzie": "MZI",
  "New Abbey": "NAB",
  "Naseby East": "NAE",
  "Nailsworth": "NAI",
  "Narberth N": "NAN",
  "Naseby West": "NAW",
  "Norham Bridge": "NBR",
  "Needles": "NDL",
  "North Duffield": "NDU",
  "New Cumnock": "NEC",
  "New Deer": "NED",
  "Needham Market E": "NEE",
  "New Galloway": "NEG",
  "Newmill": "NEM",
  "Newbury N": "NEN",
  "Newbury South": "NES",
  "Newtown": "NET",
  "Newbury Racecourse": "NEW",
  "North Hill N": "NH2",
  "North Hill": "NHL",
  "Northleach": "NLE",
  "Newmarket": "NMT",
  "Newcastle on Clun": "NOC",
  "Norman Cross": "NOR",
  "Northampton South": "NOS",
  "Northampton West": "NOW",
  "Newport Pagnall": "NPT",
  "Northallerton": "NRT",
  "N Tawton": "NTA",
  "Newark": "NWK",
  "Newent": "NWT",
  "Nympsfield Finish East": "NY1",
  "Nympsfield Finish West": "NY2",
  "Nympsfield": "NYM",
  "Oakham E": "OAE",
  "Oakington": "OAK",
  "Oban Airfield": "OBA",
  "Oban Station": "OBN",
  "Odiham": "ODI",
  "Okehampton East": "OKE",
  "Ollerton": "OLL",
  "Olney": "OLN",
  "Old Radnor": "ORA",
  "Osbournby": "OSB",
  "Oswestry": "OSW",
  "Oundle": "OUN",
  "Ousby E": "OUS",
  "Overton": "OVE",
  "Oxford East": "OXF",
  "Oxford M40 Services": "OXM",
  "Oxford North": "OXN",
  "Oxford South": "OXS",
  "Oxton": "OXT",
  "Pateley SE": "PA2",
  "Paddock Wood": "PAD",
  "Pangbourne": "PAN",
  "Papworth": "PAP",
  "Parham": "PAR",
  "Pateley Bridge": "PAT",
  "Porthcawl North": "PCN",
  "Portmoak Caravan Site": "PCS",
  "Pontefract": "PCT",
  "Peebles": "PEE",
  "Penrith": "PEI",
  "Pembroke Dock": "PEM",
  "Pendock": "PEN",
  "Peterborough": "PET",
  "Peveril Castle": "PEV",
  "Pewsey": "PEW",
  "Pitsligo": "PGO",
  "Pickenham": "PIC",
  "Penrith East": "PIE",
  "Pitsford": "PIT",
  "Pickering": "PKG",
  "Peterlee": "PLE",
  "Plumpton": "PLM",
  "Pluckley": "PLU",
  "Pitlochry": "PLY",
  "Portsmouth N": "PNT",
  "Portmoak NW": "PO1",
  "Portmoak W": "PO2",
  "Potarch Bridge": "POA",
  "Pocklington": "POC",
  "Pontesbury Hill": "POH",
  "Polegate": "POL",
  "Pontrilas": "PON",
  "Popham": "POP",
  "Portmoak Clubhouse": "POR",
  "Potton": "POT",
  "Powburn": "POW",
  "Pontypool E": "PPE",
  "Pontypool N": "PPN",
  "Port Appin": "PPP",
  "Park Control Point E": "PR1",
  "Presteigne": "PRE",
  "Prince's Risborough": "PRI",
  "Park, the": "PRK",
  "Preston North": "PRN",
  "Portree": "PRT",
  "Pershore se": "PSE",
  "Portesham": "PSH",
  "Pontardulais": "PTD",
  "Port Eynon": "PTE",
  "Petersfield South": "PTF",
  "Perth": "PTH",
  "Porthmadog": "PTM",
  "Portsmouth Tower": "PTR",
  "Petersfield West": "PTW",
  "Penwhirn Reservoir": "PWN",
  "Plymouth E": "PYE",
  "Prestatyn S": "PYS",
  "Plymouth W": "PYW",
  "Penzance N": "PZN",
  "Ramsbury": "RAB",
  "Radstock": "RAD",
  "Raglan": "RAG",
  "Ramsey": "RAM",
  "Rannoch Station": "RAN",
  "Ravensthorpe Reservoir": "RAR",
  "Rattlesden": "RAT",
  "Ravenglass N": "RAV",
  "Roybridge": "RBR",
  "Rothbury": "RBY",
  "Radway": "RDW",
  "Reading West": "REA",
  "Reedham": "REE",
  "Rattray Head": "RHD",
  "Rhigos": "RHI",
  "Rhossdhu House": "RHO",
  "Rhuddlan": "RHU",
  "Rhayader": "RHY",
  "Rivar Hill North": "RI2",
  "Richmond": "RIC",
  "Ridgewell Church": "RID",
  "Ringmer": "RIN",
  "Ripon": "RIP",
  "Rivar Hill": "RIV",
  "Ridgewell Field": "RIW",
  "Rugby Northeast": "RNE",
  "Rhynie": "RNI",
  "Roadford": "ROA",
  "Rochester": "ROC",
  "Rodney's Pillar": "ROD",
  "Rothes NE": "ROE",
  "Rothes": "ROH",
  "Ross-on-wye": "ROS",
  "Rotherham": "ROT",
  "Rougham Field": "ROU",
  "Royston": "ROY",
  "Redruth SE": "RSE",
  "Rosneath": "RSN",
  "Rothesay": "RSY",
  "Rosthwaite": "RTH",
  "Rufforth South": "RU1",
  "Rufforth North": "RU2",
  "Rubha Reidh": "RUB",
  "Rufforth": "RUF",
  "Rugby": "RUG",
  "Ruthin NE": "RUN",
  "Rushden": "RUS",
  "Rutland Water": "RUT",
  "Ruthin West": "RUW",
  "Rydal Bridge": "RYB",
  "Ryde": "RYD",
  "Rye": "RYE",
  "Sackville": "SAC",
  "Salisbury Cathedral": "SAL",
  "Sandhill Farm": "SAN",
  "Shap": "SAP",
  "Sarnesfield": "SAR",
  "Salisbury South": "SAS",
  "Sandwich": "SAW",
  "Saxthorpe": "SAX",
  "Saltby South": "SB1",
  "Saltby NW": "SB2",
  "Strubby": "SBB",
  "Santon Bridge": "SBR",
  "Saltby": "SBY",
  "Scarborough": "SCB",
  "Scoulton": "SCL",
  "Strathcarron": "SCN",
  "Scourie": "SCO",
  "St Catherine's Point": "SCP",
  "Scunthorpe N": "SCU",
  "St Davids": "SDV",
  "Seighford Hangar": "SE2",
  "Seaford East": "SEA",
  "Sedbergh": "SED",
  "Seighford Runway": "SEI",
  "Selset Reservoir": "SEL",
  "Sennybridge": "SEN",
  "Settle": "SET",
  "Severn Bridge N": "SEV",
  "Sheffield West": "SEW",
  "Stamford Bridge": "SFB",
  "Sleaford": "SFD",
  "Sheffield East": "SFE",
  "Stratford West": "SFW",
  "Stelling Windmill": "SGW",
  "Shobdon NW": "SH2",
  "Shobdon E": "SH3",
  "Shobdon West": "SH4",
  "Shaftesbury": "SHA",
  "Sherborne": "SHB",
  "Stoer Head": "SHD",
  "Sheffield North": "SHE",
  "Shirebrook Station": "SHI",
  "Salt Hill Mast": "SHL",
  "Shepton Mallett": "SHM",
  "Shobdon": "SHO",
  "Shipston-on-stour": "SHP",
  "Shrewsbury": "SHS",
  "Shrivenham N": "SHV",
  "Shrewsbury NW": "SHW",
  "Sidmouth": "SID",
  "Silverstone": "SIL",
  "Stirling South": "SIS",
  "Sittingbourne": "SIT",
  "Stirling Northwest": "SIW",
  "Sixpenny Handley": "SIX",
  "Stickney Bridge": "SKB",
  "Skeffington": "SKE",
  "Skelling Farm": "SKF",
  "Stocks Reservoir South West": "SKS",
  "Selkirk W": "SKW",
  "Sleap": "SLE",
  "Silloth": "SLL",
  "Selsey Bill": "SLS",
  "Smailholm Tower": "SMA",
  "Six Mile Bottom": "SMB",
  "St Mary's Loch": "SML",
  "Snitterfield SW": "SN2",
  "Snainton": "SNA",
  "Snitterfield": "SNI",
  "Swindon N": "SNO",
  "Staindrop": "SNP",
  "St Neots S": "SNS",
  "Stratford NW": "SNW",
  "Stratford": "SOA",
  "Sutton-on-forest": "SOF",
  "Soham": "SOH",
  "Stokenchurch South": "SOS",
  "Southam": "SOU",
  "Spalding": "SPA",
  "Spey Dam": "SPD",
  "Spean Bridge": "SPE",
  "Staplehurst": "SPH",
  "Spilsby": "SPI",
  "Spittal of Glenshee": "SPL",
  "Spinningdale Bridge": "SPN",
  "Sheppey E": "SPP",
  "Shap S": "SPS",
  "Shipton": "SPT",
  "Spurn Head North": "SPU",
  "Stroud E": "SRE",
  "Strontian": "SRN",
  "Storrington SW": "SRR",
  "Sheffield South": "SSO",
  "Stoke SW": "SSW",
  "Stafford": "STA",
  "St Boswells": "STB",
  "Stokenchurch Tower": "STC",
  "Stradishall": "STD",
  "Steyning": "STE",
  "St Fillans": "STF",
  "Stanhope": "STH",
  "Stirling": "STI",
  "Stockbridge": "STK",
  "St Neots": "STN",
  "Stone": "STO",
  "Stourport": "STP",
  "Strachan": "STR",
  "Stony Stratford": "STS",
  "Stretton": "STT",
  "Sturminster Newton": "STU",
  "Stow-on-the-wold": "STW",
  "Sutton Bank Start S": "SU1",
  "Sutton Bank Start W": "SU2",
  "Sutton Bank Control Point N": "SU3",
  "Sutton Bank Control Point S": "SU4",
  "Sudbury": "SUD",
  "Sutton Bank": "SUT",
  "Shipton under Wychwood": "SUW",
  "Strathaven": "SVN",
  "Snowdon": "SWD",
  "Swindon East": "SWE",
  "Swalcliffe": "SWL",
  "Southwell Minster": "SWM",
  "Swindon South": "SWS",
  "Swainsthorpe": "SWT",
  "Swindon W": "SWW",
  "Syre Bridge": "SYB",
  "Talgarth NW": "TA1",
  "Talgarth W": "TA2",
  "Talgarth S": "TA3",
  "Tarland": "TAD",
  "Talgarth": "TAL",
  "Tarbert": "TAR",
  "Taunton": "TAU",
  "Tavistock": "TAV",
  "Tibenham Start SE": "TB1",
  "Troutbeck": "TBK",
  "Tenby": "TBY",
  "The Camp": "TCM",
  "Tindale": "TDL",
  "Tebay": "TEB",
  "Tenterden": "TED",
  "Telford East": "TEE",
  "Telford": "TEL",
  "Tenbury Wells": "TEN",
  "Telford South": "TES",
  "Tetbury": "TET",
  "Teviothead": "TEV",
  "Tewkesbury North": "TEW",
  "Tarfside": "TFS",
  "Thame Church": "THA",
  "Todhead": "THD",
  "Thetford": "THE",
  "Thorngumbald": "THG",
  "Thirsk": "THI",
  "Thame Airfield": "THM",
  "Thornhill": "THN",
  "Thornton": "THO",
  "Thrapston": "THP",
  "Tibenham": "TIB",
  "Tideswell Church": "TID",
  "Tiverton East": "TIE",
  "Tomatin": "TIN",
  "Tiptree": "TIP",
  "Tisbury": "TIS",
  "Tiverton": "TIV",
  "Thornbury Northeast": "TNE",
  "Telford NW": "TNW",
  "Tockwith": "TOC",
  "Toddington": "TOD",
  "Tongue": "TOG",
  "Tomintoul": "TOM",
  "Tontine Inn": "TON",
  "Torver": "TOR",
  "Towcester": "TOW",
  "Tregaron": "TRE",
  "Turriff": "TRF",
  "Trowbridge": "TRO",
  "Truro NE": "TRR",
  "Truleigh": "TRU",
  "Truro West": "TRW",
  "Treyford": "TRY",
  "Telford SW": "TSW",
  "Tuxford Rail Junction": "TUJ",
  "Tulla Loch East": "TUL",
  "Tummel Bridge": "TUM",
  "Tulla Loch West": "TUW",
  "Ullswater": "ULL",
  "Ulpha": "ULP",
  "Ulverston": "ULV",
  "Upavon Hangar W": "UPA",
  "Ullapool": "UPL",
  "Uppingham N": "UPP",
  "Upwood Hangar": "UPW",
  "Usk": "USK",
  "Uttoxeter": "UTT",
  "Uffington White Horse": "UWH",
  "Vyrnwy": "VRY",
  "Waterbeck": "WAB",
  "Walford": "WAL",
  "Wantage": "WAN",
  "Watton": "WAO",
  "Warcop": "WAR",
  "Washington": "WAS",
  "Watford Gap": "WAT",
  "Whiteburn": "WBN",
  "Wetherby South": "WBS",
  "Whitby Bridge": "WBY",
  "Winchcombe": "WCB",
  "Witheridge": "WDG",
  "Windermere": "WDM",
  "Waldershare Park": "WDP",
  "Westbury Chimney": "WEB",
  "Westcott": "WEC",
  "Wellington": "WEG",
  "Welford": "WEL",
  "Wendling": "WEN",
  "Westbury": "WES",
  "Wetherby": "WET",
  "Weymouth": "WEY",
  "Wigton": "WGT",
  "Wing W": "WGW",
  "Whitchurch Hants": "WH2",
  "Whiddon Down": "WHD",
  "Whitchurch Shropshire": "WHI",
  "Whitehaven Marina": "WHM",
  "Whittington": "WHN",
  "Whiteadder Reservoir": "WHR",
  "Whitstable": "WHT",
  "Whitchurch Shropshire West": "WHW",
  "Whickham": "WIC",
  "Wingham": "WIG",
  "Wick West": "WIK",
  "Wimbleball": "WIM",
  "Wincanton": "WIN",
  "Wisbech": "WIS",
  "Wilton West": "WIW",
  "West Lomond Hill": "WLD",
  "Willersley": "WLL",
  "Wells": "WLS",
  "Waternish Point": "WLT",
  "Worlingworth": "WLW",
  "Woolley Down": "WLY",
  "Welshpool NE": "WNE",
  "Wing": "WNG",
  "Wantage Northwest": "WNW",
  "Weston Finish Point": "WO2",
  "Woburn Abbey": "WOB",
  "Worcester Racecourse": "WOC",
  "Woodall Services": "WOD",
  "Woore": "WOE",
  "Weston-on-the-green": "WOG",
  "Wooler East": "WOL",
  "Woburn": "WOM",
  "Walton on Naze Pier": "WON",
  "Wooler": "WOO",
  "Worcester": "WOR",
  "Wragby": "WRA",
  "Wrexham": "WRE",
  "Workington": "WRK",
  "Wormingford": "WRM",
  "Wroughton": "WRO",
  "Winslow": "WSL",
  "Wattisham": "WSM",
  "Waterbeach N": "WTB",
  "Worthing": "WTH",
  "Worthen": "WTM",
  "Watlington": "WTN",
  "Wast Water E": "WWE",
  "Wast Water W": "WWW",
  "Wylye": "WYL",
  "Wymondham": "WYM",
  "Yate": "YAT",
  "Yeovil Reservoir": "YEO",
  "Yetholm": "YET",
  "York East": "YOE",
  "York": "YOR",
  "Yeovilton": "YTN",
  "Yattendon": "YTT"
}

module.exports = exports;
