const turnpoints = {
    yattendon: 'YTT',
    yeovilton: 'YTN',
    york: 'YOR',
    'york east': 'YOE',
    yetholm: 'YET',
    'yeovil reservoir': 'YEO',
    yate: 'YAT',
    wymondham: 'WYM',
    wylye: 'WYL',
    'wast water w': 'WWW',
    'wast water e': 'WWE',
    watlington: 'WTN',
    worthen: 'WTM',
    worthing: 'WTH',
    'waterbeach n': 'WTB',
    wattisham: 'WSM',
    winslow: 'WSL',
    wroughton: 'WRO',
    wormingford: 'WRM',
    workington: 'WRK',
    wrexham: 'WRE',
    wragby: 'WRA',
    worcester: 'WOR',
    wooler: 'WOO',
    'walton on naze pier': 'WON',
    woburn: 'WOM',
    'wooler east': 'WOL',
    'weston-on-the-green': 'WOG',
    woore: 'WOE',
    'woodall services': 'WOD',
    'worcester racecourse': 'WOC',
    'woburn abbey': 'WOB',
    'weston finish point': 'WO2',
    'wantage northwest': 'WNW',
    wing: 'WNG',
    'welshpool ne': 'WNE',
    'woolley down': 'WLY',
    worlingworth: 'WLW',
    'waternish point': 'WLT',
    wells: 'WLS',
    willersley: 'WLL',
    'west lomond hill': 'WLD',
    'wilton west': 'WIW',
    wisbech: 'WIS',
    wincanton: 'WIN',
    wimbleball: 'WIM',
    'wick west': 'WIK',
    wingham: 'WIG',
    whickham: 'WIC',
    'whitchurch shropshire west': 'WHW',
    whitstable: 'WHT',
    'whiteadder reservoir': 'WHR',
    whittington: 'WHN',
    'whitehaven marina': 'WHM',
    'whitchurch shropshire': 'WHI',
    'whiddon down': 'WHD',
    'whitchurch hants': 'WH2',
    'wing w': 'WGW',
    wigton: 'WGT',
    weymouth: 'WEY',
    wetherby: 'WET',
    westbury: 'WES',
    wendling: 'WEN',
    welford: 'WEL',
    wellington: 'WEG',
    westcott: 'WEC',
    'westbury chimney': 'WEB',
    'waldershare park': 'WDP',
    windermere: 'WDM',
    witheridge: 'WDG',
    winchcombe: 'WCB',
    'whitby bridge': 'WBY',
    'wetherby south': 'WBS',
    whiteburn: 'WBN',
    'watford gap': 'WAT',
    washington: 'WAS',
    warcop: 'WAR',
    watton: 'WAO',
    wantage: 'WAN',
    walford: 'WAL',
    waterbeck: 'WAB',
    vyrnwy: 'VRY',
    'uffington white horse': 'UWH',
    uttoxeter: 'UTT',
    usk: 'USK',
    'upwood hangar': 'UPW',
    'uppingham n': 'UPP',
    ullapool: 'UPL',
    'upavon hangar w': 'UPA',
    ulverston: 'ULV',
    ulpha: 'ULP',
    ullswater: 'ULL',
    'tulla loch west': 'TUW',
    'tummel bridge': 'TUM',
    'tulla loch east': 'TUL',
    'tuxford rail junction': 'TUJ',
    'telford sw': 'TSW',
    treyford: 'TRY',
    'truro west': 'TRW',
    truleigh: 'TRU',
    'truro ne': 'TRR',
    trowbridge: 'TRO',
    turriff: 'TRF',
    tregaron: 'TRE',
    towcester: 'TOW',
    torver: 'TOR',
    'tontine inn': 'TON',
    tomintoul: 'TOM',
    tongue: 'TOG',
    toddington: 'TOD',
    tockwith: 'TOC',
    'telford nw': 'TNW',
    'thornbury northeast': 'TNE',
    tiverton: 'TIV',
    tisbury: 'TIS',
    tiptree: 'TIP',
    tomatin: 'TIN',
    'tiverton east': 'TIE',
    'tideswell church': 'TID',
    tibenham: 'TIB',
    thrapston: 'THP',
    thornton: 'THO',
    thornhill: 'THN',
    'thame airfield': 'THM',
    thirsk: 'THI',
    thorngumbald: 'THG',
    thetford: 'THE',
    todhead: 'THD',
    'thame church': 'THA',
    tarfside: 'TFS',
    'tewkesbury north': 'TEW',
    teviothead: 'TEV',
    tetbury: 'TET',
    'telford south': 'TES',
    'tenbury wells': 'TEN',
    telford: 'TEL',
    'telford east': 'TEE',
    tenterden: 'TED',
    tebay: 'TEB',
    tindale: 'TDL',
    'the camp': 'TCM',
    tenby: 'TBY',
    troutbeck: 'TBK',
    'tibenham start se': 'TB1',
    tavistock: 'TAV',
    taunton: 'TAU',
    tarbert: 'TAR',
    talgarth: 'TAL',
    tarland: 'TAD',
    'talgarth s': 'TA3',
    'talgarth w': 'TA2',
    'talgarth nw': 'TA1',
    'syre bridge': 'SYB',
    'swindon w': 'SWW',
    swainsthorpe: 'SWT',
    'swindon south': 'SWS',
    'southwell minster': 'SWM',
    swalcliffe: 'SWL',
    'swindon east': 'SWE',
    snowdon: 'SWD',
    strathaven: 'SVN',
    'shipton under wychwood': 'SUW',
    'sutton bank': 'SUT',
    sudbury: 'SUD',
    'sutton bank control point s': 'SU4',
    'sutton bank control point n': 'SU3',
    'sutton bank start w': 'SU2',
    'sutton bank start s': 'SU1',
    'stow-on-the-wold': 'STW',
    'sturminster newton': 'STU',
    stretton: 'STT',
    'stony stratford': 'STS',
    strachan: 'STR',
    stourport: 'STP',
    stone: 'STO',
    'st neots': 'STN',
    stockbridge: 'STK',
    stirling: 'STI',
    stanhope: 'STH',
    'st fillans': 'STF',
    steyning: 'STE',
    stradishall: 'STD',
    'stokenchurch tower': 'STC',
    'st boswells': 'STB',
    stafford: 'STA',
    'stoke sw': 'SSW',
    'sheffield south': 'SSO',
    'storrington sw': 'SRR',
    strontian: 'SRN',
    'stroud e': 'SRE',
    'spurn head north': 'SPU',
    shipton: 'SPT',
    'shap s': 'SPS',
    'sheppey e': 'SPP',
    'spinningdale bridge': 'SPN',
    'spittal of glenshee': 'SPL',
    spilsby: 'SPI',
    staplehurst: 'SPH',
    'spean bridge': 'SPE',
    'spey dam': 'SPD',
    spalding: 'SPA',
    southam: 'SOU',
    'stokenchurch south': 'SOS',
    soham: 'SOH',
    'sutton-on-forest': 'SOF',
    stratford: 'SOA',
    'stratford nw': 'SNW',
    'st neots s': 'SNS',
    staindrop: 'SNP',
    'swindon n': 'SNO',
    snitterfield: 'SNI',
    snainton: 'SNA',
    'snitterfield sw': 'SN2',
    'st mary\'s loch': 'SML',
    'six mile bottom': 'SMB',
    'smailholm tower': 'SMA',
    'selsey bill': 'SLS',
    silloth: 'SLL',
    sleap: 'SLE',
    'selkirk w': 'SKW',
    'stocks reservoir south west': 'SKS',
    'skelling farm': 'SKF',
    skeffington: 'SKE',
    'stickney bridge': 'SKB',
    'sixpenny handley': 'SIX',
    'stirling northwest': 'SIW',
    sittingbourne: 'SIT',
    'stirling south': 'SIS',
    silverstone: 'SIL',
    sidmouth: 'SID',
    'shrewsbury nw': 'SHW',
    'shrivenham n': 'SHV',
    shrewsbury: 'SHS',
    'shipston-on-stour': 'SHP',
    shobdon: 'SHO',
    'shepton mallett': 'SHM',
    'salt hill mast': 'SHL',
    'shirebrook station': 'SHI',
    'sheffield north': 'SHE',
    'stoer head': 'SHD',
    sherborne: 'SHB',
    shaftesbury: 'SHA',
    'shobdon west': 'SH4',
    'shobdon e': 'SH3',
    'shobdon nw': 'SH2',
    'stelling windmill': 'SGW',
    'stratford west': 'SFW',
    'sheffield east': 'SFE',
    sleaford: 'SFD',
    'stamford bridge': 'SFB',
    'sheffield west': 'SEW',
    'severn bridge n': 'SEV',
    settle: 'SET',
    sennybridge: 'SEN',
    'selset reservoir': 'SEL',
    'seighford runway': 'SEI',
    sedbergh: 'SED',
    'seaford east': 'SEA',
    'seighford hangar': 'SE2',
    'st davids': 'SDV',
    'scunthorpe n': 'SCU',
    'st catherine\'s point': 'SCP',
    scourie: 'SCO',
    strathcarron: 'SCN',
    scoulton: 'SCL',
    scarborough: 'SCB',
    saltby: 'SBY',
    'santon bridge': 'SBR',
    strubby: 'SBB',
    'saltby nw': 'SB2',
    'saltby south': 'SB1',
    saxthorpe: 'SAX',
    sandwich: 'SAW',
    'salisbury south': 'SAS',
    sarnesfield: 'SAR',
    shap: 'SAP',
    'sandhill farm': 'SAN',
    'salisbury cathedral': 'SAL',
    sackville: 'SAC',
    rye: 'RYE',
    ryde: 'RYD',
    'rydal bridge': 'RYB',
    'ruthin west': 'RUW',
    'rutland water': 'RUT',
    rushden: 'RUS',
    'ruthin ne': 'RUN',
    rugby: 'RUG',
    rufforth: 'RUF',
    'rubha reidh': 'RUB',
    'rufforth north': 'RU2',
    'rufforth south': 'RU1',
    rosthwaite: 'RTH',
    rothesay: 'RSY',
    rosneath: 'RSN',
    'redruth se': 'RSE',
    royston: 'ROY',
    'rougham field': 'ROU',
    rotherham: 'ROT',
    'ross-on-wye': 'ROS',
    rothes: 'ROH',
    'rothes ne': 'ROE',
    'rodney\'s pillar': 'ROD',
    rochester: 'ROC',
    roadford: 'ROA',
    rhynie: 'RNI',
    'rugby northeast': 'RNE',
    'ridgewell field': 'RIW',
    'rivar hill': 'RIV',
    ripon: 'RIP',
    ringmer: 'RIN',
    'ridgewell church': 'RID',
    richmond: 'RIC',
    'rivar hill north': 'RI2',
    rhayader: 'RHY',
    rhuddlan: 'RHU',
    'rhossdhu house': 'RHO',
    rhigos: 'RHI',
    'rattray head': 'RHD',
    reedham: 'REE',
    'reading west': 'REA',
    radway: 'RDW',
    rothbury: 'RBY',
    roybridge: 'RBR',
    'ravenglass n': 'RAV',
    rattlesden: 'RAT',
    'ravensthorpe reservoir': 'RAR',
    'rannoch station': 'RAN',
    ramsey: 'RAM',
    raglan: 'RAG',
    radstock: 'RAD',
    ramsbury: 'RAB',
    'penzance n': 'PZN',
    'plymouth w': 'PYW',
    'prestatyn s': 'PYS',
    'plymouth e': 'PYE',
    'penwhirn reservoir': 'PWN',
    'petersfield west': 'PTW',
    'portsmouth tower': 'PTR',
    porthmadog: 'PTM',
    perth: 'PTH',
    'petersfield south': 'PTF',
    'port eynon': 'PTE',
    pontardulais: 'PTD',
    portesham: 'PSH',
    'pershore se': 'PSE',
    portree: 'PRT',
    'preston north': 'PRN',
    'park, the': 'PRK',
    'prince\'s risborough': 'PRI',
    presteigne: 'PRE',
    'park control point e': 'PR1',
    'port appin': 'PPP',
    'pontypool n': 'PPN',
    'pontypool e': 'PPE',
    powburn: 'POW',
    potton: 'POT',
    'portmoak clubhouse': 'POR',
    popham: 'POP',
    pontrilas: 'PON',
    polegate: 'POL',
    'pontesbury hill': 'POH',
    pocklington: 'POC',
    'potarch bridge': 'POA',
    'portmoak w': 'PO2',
    'portmoak nw': 'PO1',
    'portsmouth n': 'PNT',
    pitlochry: 'PLY',
    pluckley: 'PLU',
    plumpton: 'PLM',
    peterlee: 'PLE',
    pickering: 'PKG',
    pitsford: 'PIT',
    'penrith east': 'PIE',
    pickenham: 'PIC',
    pitsligo: 'PGO',
    pewsey: 'PEW',
    'peveril castle': 'PEV',
    peterborough: 'PET',
    pendock: 'PEN',
    'pembroke dock': 'PEM',
    penrith: 'PEI',
    peebles: 'PEE',
    pontefract: 'PCT',
    'portmoak caravan site': 'PCS',
    'porthcawl north': 'PCN',
    'pateley bridge': 'PAT',
    parham: 'PAR',
    papworth: 'PAP',
    pangbourne: 'PAN',
    'paddock wood': 'PAD',
    'pateley se': 'PA2',
    oxton: 'OXT',
    'oxford south': 'OXS',
    'oxford north': 'OXN',
    'oxford m40 services': 'OXM',
    'oxford east': 'OXF',
    overton: 'OVE',
    'ousby e': 'OUS',
    oundle: 'OUN',
    oswestry: 'OSW',
    osbournby: 'OSB',
    'old radnor': 'ORA',
    olney: 'OLN',
    ollerton: 'OLL',
    'okehampton east': 'OKE',
    odiham: 'ODI',
    'oban station': 'OBN',
    'oban airfield': 'OBA',
    oakington: 'OAK',
    'oakham e': 'OAE',
    nympsfield: 'NYM',
    'nympsfield finish west': 'NY2',
    'nympsfield finish east': 'NY1',
    newent: 'NWT',
    newark: 'NWK',
    'n tawton': 'NTA',
    northallerton: 'NRT',
    'newport pagnall': 'NPT',
    'northampton west': 'NOW',
    'northampton south': 'NOS',
    'norman cross': 'NOR',
    'newcastle on clun': 'NOC',
    newmarket: 'NMT',
    northleach: 'NLE',
    'north hill': 'NHL',
    'north hill n': 'NH2',
    'newbury racecourse': 'NEW',
    newtown: 'NET',
    'newbury south': 'NES',
    'newbury n': 'NEN',
    newmill: 'NEM',
    'new galloway': 'NEG',
    'needham market e': 'NEE',
    'new deer': 'NED',
    'new cumnock': 'NEC',
    'north duffield': 'NDU',
    needles: 'NDL',
    'norham bridge': 'NBR',
    'naseby west': 'NAW',
    'narberth n': 'NAN',
    nailsworth: 'NAI',
    'naseby east': 'NAE',
    'new abbey': 'NAB',
    monzie: 'MZI',
    mynd: 'MYN',
    'mynd n': 'MY3',
    'mynd s': 'MY2',
    mallwyd: 'MWD',
    methven: 'MVN',
    murton: 'MUT',
    mursley: 'MUR',
    mundford: 'MUN',
    'mumbles head': 'MUM',
    'mudford gate': 'MUD',
    montrose: 'MTR',
    'melton mast': 'MTM',
    'moota hill': 'MTH',
    'mottisfont station': 'MTF',
    'mansfield se': 'MSE',
    maryport: 'MRY',
    'market rasen': 'MRN',
    marham: 'MRM',
    'margate e': 'MRE',
    'moy lodge': 'MOY',
    'moulton church': 'MOU',
    'mortimer church': 'MOT',
    mossat: 'MOS',
    'moreton-in-marsh': 'MOR',
    morpeth: 'MOP',
    'muir of ord': 'MOO',
    montgomery: 'MON',
    monmouth: 'MOM',
    monkton: 'MOK',
    'millom nw': 'MNW',
    'menai strait': 'MNS',
    'maryport ne': 'MNE',
    milton: 'MLT',
    molton: 'MLN',
    melmerby: 'MLM',
    'mellon charles': 'MLL',
    'midhurst west': 'MIW',
    milnthorpe: 'MIT',
    mintlaw: 'MIN',
    'midhurst mast': 'MIM',
    milfield: 'MIL',
    'mingary pier': 'MIG',
    micheldever: 'MIC',
    'mansfield ne': 'MFD',
    'mexborough s': 'MEX',
    'west meon hut': 'MEW',
    'melton mowbray': 'MET',
    mere: 'MER',
    mendlesham: 'MEN',
    membury: 'MEM',
    melksham: 'MEL',
    'east meon': 'MEE',
    measham: 'MEA',
    'maidstone north': 'MDN',
    march: 'MCH',
    manby: 'MBY',
    'melbury bubb': 'MBU',
    'montford bridge': 'MBR',
    'market bosworth': 'MBO',
    mablethorpe: 'MBL',
    'market weighton': 'MAW',
    matlock: 'MAT',
    masham: 'MAS',
    marlborough: 'MAR',
    manton: 'MAN',
    malmesbury: 'MAM',
    malton: 'MAL',
    'maidstone east': 'MAI',
    'market harborough': 'MAH',
    'marlborough e': 'MAE',
    'market deeping': 'MAD',
    'machynlleth station': 'MAC',
    lyveden: 'LYV',
    'ladybower reservoir': 'LYR',
    'lyneham a/f': 'LYN',
    'leyland north east': 'LYD',
    'lewes nw': 'LWN',
    'low lorton': 'LWL',
    lavenham: 'LVN',
    'loch venachar': 'LVE',
    lutterworth: 'LUT',
    'lussa loch s': 'LUS',
    luncarty: 'LUN',
    ludlow: 'LUD',
    longtown: 'LTN',
    langtoft: 'LTF',
    'lincoln southwest': 'LSW',
    'long sutton': 'LSU',
    liss: 'LSS',
    'loch seilich n': 'LSN',
    llandysul: 'LSL',
    lanark: 'LRK',
    'little rissington': 'LRI',
    lowick: 'LOW',
    louth: 'LOU',
    'loch quoich east': 'LOQ',
    longleat: 'LON',
    'lake of menteith': 'LOM',
    'loch lochy north east': 'LOL',
    'loch kinord': 'LOK',
    'loch gairloch se': 'LOG',
    'linn of dee': 'LOD',
    lockerbie: 'LOC',
    lochailort: 'LOA',
    'lichfield ne': 'LNE',
    'loch moy': 'LMY',
    'leominster nw': 'LMW',
    'loch muick': 'LMU',
    ledmore: 'LMR',
    'loch morlich': 'LMO',
    'loch mullardoch east': 'LMD',
    lochmaben: 'LMB',
    'long marston': 'LMA',
    'llandrindod wells': 'LLW',
    'loch lomond tarbet': 'LLT',
    llantysilio: 'LLS',
    llandeilo: 'LLO',
    llanrwst: 'LLN',
    llanidloes: 'LLI',
    'llangynidr bridge': 'LLG',
    'lleweni parc': 'LLE',
    llandovery: 'LLD',
    'llanfair caereinion': 'LLC',
    llanbadarn: 'LLB',
    llangollen: 'LLA',
    'liskeard se': 'LKD',
    littleport: 'LIT',
    lismore: 'LIS',
    liphook: 'LIP',
    lochgoilhead: 'LGO',
    'loch garry n': 'LGN',
    lochgilphead: 'LGI',
    'loch laggan north east': 'LGG',
    llanfyllin: 'LFN',
    'leighton buzzard': 'LEZ',
    leyburn: 'LEY',
    'lewes north': 'LEW',
    'leicester south': 'LES',
    'loch errochty east': 'LER',
    leominster: 'LEO',
    'leicester north': 'LEN',
    'loch eil west': 'LEL',
    leck: 'LEK',
    'leicester m1 services': 'LEI',
    leadenham: 'LEH',
    'lee-on-solent': 'LEE',
    ledbury: 'LED',
    lochearnhead: 'LEA',
    lindores: 'LDR',
    'laggan dam': 'LDM',
    'lochindorb castle': 'LDB',
    'lower clopton': 'LCL',
    lanchester: 'LCH',
    'llyn celyn nw': 'LCE',
    'leighton buzzard ne': 'LBZ',
    lochbuie: 'LBU',
    'laggan bridge': 'LBR',
    lambourn: 'LBN',
    'loch bradan e': 'LBE',
    'longbridge deverill': 'LBD',
    launceston: 'LAU',
    latheron: 'LAT',
    'lasham clubhouse': 'LAS',
    lattrig: 'LAR',
    lapford: 'LAP',
    langham: 'LAN',
    lampeter: 'LAM',
    lairg: 'LAI',
    langport: 'LAG',
    'llanelli east': 'LAE',
    lauder: 'LAD',
    'lasham golden pot': 'LA8',
    'lasham finish west': 'LA7',
    'lasham start north': 'LA6',
    'lasham west': 'LA5',
    'lasham start south': 'LA4',
    'lasham church': 'LA3',
    'lasham start east': 'LA2',
    'lasham start southeast': 'LA1',
    kyleakin: 'KYL',
    kibworth: 'KWO',
    kinlochewe: 'KWE',
    kilmington: 'KTN',
    keith: 'KTH',
    'kirkby stephen station': 'KST',
    'kingston bagpuize': 'KSB',
    kirriemuir: 'KRM',
    kirkbymoorside: 'KRB',
    knowstone: 'KNO',
    knighton: 'KNI',
    knaresborough: 'KNA',
    kenmore: 'KMR',
    kirkmichael: 'KML',
    kentmere: 'KME',
    'king\'s lynn': 'KLY',
    kinloss: 'KLS',
    'kirkby lonsdale': 'KLO',
    killin: 'KLN',
    kilham: 'KLH',
    'kirton-in-lindsey': 'KIR',
    kippen: 'KIP',
    kineton: 'KIN',
    kingham: 'KIM',
    kilcreggan: 'KIL',
    kirkharle: 'KIK',
    kingussie: 'KIG',
    'kielder reservoir': 'KIE',
    kidderminster: 'KID',
    kinclaven: 'KIC',
    kinbrace: 'KIB',
    kingsclere: 'KGS',
    'kexby bridge': 'KEX',
    'kettering south': 'KES',
    kenley: 'KEN',
    'kempock point': 'KEM',
    kelso: 'KEL',
    keswick: 'KEK',
    keevil: 'KEE',
    kendal: 'KDL',
    kincraig: 'KCG',
    'kielder castle': 'KCA',
    jedburgh: 'JED',
    'iwerne minster': 'IWE',
    'ivybridge east': 'IVY',
    invershin: 'IVS',
    islip: 'ISL',
    'inverness se': 'ISE',
    'ipswich e': 'IPE',
    inverary: 'INV',
    inverness: 'INS',
    inchkinloch: 'INK',
    ingleton: 'ING',
    insch: 'INC',
    ilsley: 'ILS',
    'hay east': 'HYE',
    haltwistle: 'HWL',
    'halfway house': 'HWH',
    haverfordwest: 'HVW',
    'havant nw': 'HVT',
    'havant s': 'HVS',
    'husbands bosworth': 'HUS',
    'hurstbourne tarrant': 'HUR',
    hungerford: 'HUN',
    'humber bridge': 'HUM',
    huntly: 'HTY',
    'honington airfield': 'HTN',
    'hornsea mere': 'HSM',
    hathersage: 'HSG',
    hawes: 'HSE',
    'hartside top': 'HRT',
    harrietsham: 'HRR',
    harpley: 'HPY',
    'howden dam': 'HOW',
    'hesket old town': 'HOT',
    horncastle: 'HOR',
    holsworthy: 'HOL',
    honeybourne: 'HOB',
    huntercombe: 'HNT',
    'hungerford north': 'HNN',
    helmsley: 'HLM',
    'hunstanton lighthouse': 'HLH',
    'hinton in the hedges': 'HIN',
    hinckley: 'HIC',
    'hinton start w': 'HI1',
    'hembury hill': 'HHL',
    highham: 'HGM',
    hexham: 'HEX',
    'heugh head': 'HEU',
    henstridge: 'HES',
    'hereford racecourse': 'HER',
    helensburgh: 'HEL',
    'heathfield e': 'HEE',
    'hereford cathedral': 'HEC',
    hardwick: 'HDW',
    helmsdale: 'HDL',
    haddington: 'HDD',
    herstmonceux: 'HCX',
    'haydon bridge': 'HBR',
    'hb control point west': 'HB6',
    'hb control point east': 'HB5',
    'hb east': 'HB4',
    'hb start east': 'HB3',
    'hb start north': 'HB2',
    'hb start west': 'HB1',
    'hay-on-wye': 'HAY',
    hawkhurst: 'HAW',
    haverhill: 'HAV',
    hatherleigh: 'HAT',
    hastings: 'HAS',
    harting: 'HAR',
    'harrogate north': 'HAN',
    halton: 'HAL',
    hawick: 'HAK',
    hailsham: 'HAI',
    halesworth: 'HAE',
    halesland: 'HAD',
    'hay bluff': 'HAB',
    'great yarmouth s': 'GYS',
    'grantown sw': 'GWS',
    'goodwood grandstand': 'GWD',
    garve: 'GVE',
    'guisborough sw': 'GUW',
    guisborough: 'GUI',
    'great witley': 'GTW',
    'grantown s': 'GTS',
    grantown: 'GTN',
    glassonby: 'GSS',
    'grafham water': 'GRW',
    'great rundale tarn': 'GRT',
    grassington: 'GRS',
    grosmont: 'GRO',
    greenlaw: 'GRN',
    'great malvern': 'GRM',
    'gransden lodge': 'GRL',
    'grimwith reservoir': 'GRI',
    'great ashfield': 'GRF',
    'grasmere church': 'GRC',
    grantham: 'GRA',
    'gransden e': 'GR4',
    'gransden w': 'GR3',
    'gransden se': 'GR2',
    'gransden nw': 'GR1',
    goring: 'GOR',
    'goole ne': 'GOO',
    'goole n': 'GO2',
    grains: 'GNS',
    'grantown ne': 'GNE',
    gairlochy: 'GLY',
    'glenlatterach dam n': 'GLT',
    'gloucester south': 'GLS',
    'gloucester west': 'GLO',
    gleneagles: 'GLN',
    glenforsa: 'GLF',
    glendevon: 'GLE',
    'gelt bridge': 'GLB',
    glastonbury: 'GLA',
    gisburn: 'GIS',
    gillingham: 'GIL',
    'garsdale head': 'GHD',
    'glen falloch': 'GFL',
    'glenfarg reservoir e': 'GFG',
    'glenfiddich lodge': 'GFD',
    'gretna services': 'GES',
    gordon: 'GDN',
    'great dun fell': 'GDF',
    glyndebourne: 'GDE',
    'glen dee bridge': 'GDB',
    'glasbury bridge': 'GBR',
    'great bedwyn': 'GBE',
    'gribbin head': 'GBB',
    gaydon: 'GAY',
    'gateshead east': 'GAT',
    garten: 'GAR',
    gallowfauld: 'GAL',
    gainsborough: 'GAI',
    'gargrave west': 'GAG',
    garforth: 'GAF',
    garboldisham: 'GAB',
    galashiels: 'GAA',
    'gainsborough power station': 'GA2',
    feltwell: 'FWL',
    'fort william': 'FTW',
    framlingham: 'FRW',
    frome: 'FRO',
    fridaythorpe: 'FRI',
    freuchie: 'FRE',
    foxton: 'FOX',
    fovant: 'FOV',
    foston: 'FOS',
    fordingbridge: 'FOR',
    folkestone: 'FOL',
    fordoun: 'FOD',
    'fort augustus': 'FOA',
    'falmouth nw': 'FNW',
    'fort william ne': 'FNE',
    'four marks': 'FMA',
    flamborough: 'FLA',
    fishguard: 'FIS',
    finavon: 'FIN',
    finmere: 'FIM',
    filey: 'FIL',
    'firle beacon': 'FIB',
    forfar: 'FFR',
    'felixstowe pier': 'FEX',
    fettercairn: 'FET',
    feshiebridge: 'FES',
    ferness: 'FER',
    'fenny compton': 'FEN',
    fearnan: 'FEA',
    'feshie s': 'FE5',
    'feshie watersports': 'FE4',
    'feshie descent point': 'FE3',
    'feshie start n': 'FE2',
    'feshie airstrip': 'FE1',
    fraserburgh: 'FBG',
    'falkirk west': 'FAW',
    faversham: 'FAV',
    faringdon: 'FAR',
    falgunzeon: 'FAL',
    fakenham: 'FAK',
    eyebrook: 'EYE',
    'ennerdale water w': 'EWW',
    evesham: 'EVE',
    ettington: 'ETT',
    etal: 'ETL',
    etchingham: 'ETC',
    'eastbourne nw': 'ENW',
    enstone: 'ENS',
    ely: 'ELY',
    'elmswell w': 'ELM',
    ellesmere: 'ELL',
    'elkstone s': 'ELK',
    'eggesford n': 'EGG',
    edzell: 'EDZ',
    edgehill: 'EDG',
    eastwell: 'EAW',
    eastgate: 'EAT',
    easterton: 'EAS',
    earith: 'EAR',
    eaglescott: 'EAG',
    dyserth: 'DYS',
    'danbury n': 'DYN',
    dalwhinnie: 'DWI',
    'daventry n': 'DVN',
    'dursley nw': 'DUY',
    dufton: 'DUT',
    duns: 'DUS',
    durham: 'DUR',
    'dunstable airfield': 'DUN',
    dumfries: 'DUM',
    dulverton: 'DUL',
    dufftown: 'DUF',
    duncton: 'DUC',
    donington: 'DTN',
    'dursley sw': 'DSW',
    'daventry se': 'DSE',
    drumshade: 'DRU',
    'denbigh ridge s': 'DRS',
    droitwich: 'DRO',
    darlton: 'DRL',
    driffield: 'DRI',
    'droma bridge': 'DRB',
    'downham market': 'DOW',
    'dover marina': 'DOV',
    doune: 'DOU',
    dorchester: 'DOR',
    dollar: 'DOL',
    dolgellau: 'DOG',
    docking: 'DOC',
    'doncaster northwest': 'DNW',
    duntulm: 'DNT',
    'dunstable roundabout': 'DNS',
    dunoon: 'DNN',
    dunning: 'DNG',
    'durham northeast': 'DNE',
    'dunbar se': 'DNB',
    dalston: 'DLT',
    dallas: 'DLS',
    'dale bridge': 'DLB',
    'dunkery beacon': 'DKY',
    dunkeld: 'DKD',
    ditchlingbeacon: 'DIT',
    diss: 'DIS',
    dingwall: 'DIN',
    didcot: 'DID',
    'dalton-in-furness': 'DFU',
    duffield: 'DFF',
    devizes: 'DEV',
    detling: 'DET',
    derwent: 'DER',
    'depden water tower': 'DEP',
    denbigh: 'DEN',
    deddington: 'DED',
    deal: 'DEA',
    'devil\'s dyke': 'DDK',
    'devil\'s bridge': 'DBR',
    dunblane: 'DBN',
    darwell: 'DAW',
    darlington: 'DAR',
    danby: 'DAN',
    dalmally: 'DAM',
    dallachy: 'DAL',
    'conwy s': 'CWY',
    chatsworth: 'CWT',
    'cwmbran sw': 'CWS',
    'carsington water': 'CWR',
    corwen: 'CWN',
    'crewe east': 'CWE',
    'chipping warden': 'CWA',
    'craven arms': 'CVN',
    'currock hill': 'CUR',
    cupar: 'CUP',
    clun: 'CUN',
    cullompton: 'CUL',
    'clunbury hill': 'CU2',
    cottam: 'CTT',
    'charlestown ne': 'CTN',
    catterick: 'CTK',
    'crathie bridge': 'CTH',
    colsterworth: 'CSW',
    'cross hands': 'CSS',
    coniston: 'CSN',
    'crask bridge': 'CSK',
    'cosford airfield': 'CSF',
    'canterbury south east': 'CSE',
    'cray reservoir': 'CRY',
    'crediton west': 'CRW',
    carron: 'CRR',
    'cromer pier': 'CRP',
    'crowland bridge': 'CRO',
    crinan: 'CRN',
    'crowland a/f': 'CRL',
    crewkerne: 'CRK',
    crianlarich: 'CRI',
    cerrig: 'CRG',
    'crediton station': 'CRE',
    cricklade: 'CRD',
    crick: 'CRC',
    cranbrook: 'CRB',
    'cranwell north': 'CRA',
    'chippenham w': 'CPW',
    'clapham reservoir n': 'CPN',
    camphill: 'CPH',
    'camphill chimney': 'CP2',
    'camphill start/finish south': 'CP1',
    'colchester west': 'COW',
    'coupar angus': 'COU',
    'colt crag reservoir': 'COT',
    'cosford junction': 'COS',
    corby: 'COR',
    condover: 'CON',
    comrie: 'COM',
    cocking: 'COK',
    coldingham: 'COH',
    'corby glen': 'COG',
    crocketford: 'COF',
    'corwen ne': 'COE',
    coldstream: 'COD',
    colchester: 'COC',
    'corby south': 'COB',
    'charlestown of aberlour': 'COA',
    'conwy bridge': 'CNY',
    'cirencester nw': 'CNW',
    chinnor: 'CNR',
    carno: 'CNO',
    'corndon hill': 'CNN',
    connel: 'CNL',
    'canterbury north east': 'CNE',
    cockermouth: 'CMO',
    carmarthen: 'CMN',
    'cheltenham east': 'CME',
    'callaly castle': 'CLY',
    clunas: 'CLU',
    'corran lighthouse': 'CLT',
    culmstock: 'CLS',
    'clyffe pypard': 'CLP',
    clova: 'CLO',
    'calne w': 'CLN',
    chilham: 'CLM',
    carlisle: 'CLL',
    challock: 'CLK',
    clitheroe: 'CLI',
    clee: 'CLE',
    'culdrose a/f': 'CLD',
    'clacton e': 'CLC',
    claydon: 'CLA',
    'challock east': 'CL3',
    'challock chalk pit': 'CL2',
    chicklade: 'CKL',
    'cirencester church': 'CIR',
    cinderford: 'CIN',
    charwelton: 'CHW',
    chieveley: 'CHV',
    'church houses': 'CHU',
    chatteris: 'CHT',
    'chelmsford s': 'CHS',
    'charterhall field': 'CHR',
    chipping: 'CHP',
    'chorley west': 'CHO',
    'chipping norton': 'CHN',
    cheltenham: 'CHL',
    chirk: 'CHK',
    'chichester w': 'CHI',
    chedworth: 'CHE',
    chesterfield: 'CHD',
    'chipping campden': 'CHC',
    charlbury: 'CHB',
    chard: 'CHA',
    cherington: 'CGT',
    croglin: 'CGL',
    corgarf: 'CGF',
    crieff: 'CFF',
    'chollerford bridge': 'CFB',
    cowes: 'CES',
    'cerne abbas': 'CER',
    'clattershaws dam s': 'CDS',
    'castle douglas sw': 'CDO',
    'cadbury cross': 'CCX',
    'clay cross reservoir': 'CCR',
    crickhowell: 'CCL',
    'castle carrock dam nw': 'CCK',
    'carreg cennen castle': 'CCC',
    carrbridge: 'CBR',
    chilbolton: 'CBN',
    'carisbrooke castle': 'CBK',
    'creagan bridge': 'CBG',
    'conisbrough castle': 'CBC',
    'carter bar': 'CBA',
    'caxton gibbet': 'CAX',
    'cambridge west': 'CAW',
    canterbury: 'CAT',
    'cambridge south': 'CAS',
    'carlton moor': 'CAR',
    canonbie: 'CAO',
    cannock: 'CAN',
    'cambridge north': 'CAM',
    'calvert rail junction': 'CAL',
    cairnwell: 'CAI',
    'castle howard': 'CAH',
    'canterbury east': 'CAE',
    callander: 'CAD',
    'candover church': 'CAC',
    'cambridge se': 'CAB',
    bwlch: 'BWL',
    'bridgwater e': 'BWE',
    bovington: 'BVT',
    belvoir: 'BVR',
    beauly: 'BUY',
    buxton: 'BUX',
    'butser hill': 'BUT',
    'burton upon stather': 'BUS',
    bungay: 'BUN',
    bullington: 'BUL',
    buckfastleigh: 'BUK',
    'builth wells': 'BUI',
    'burnhope reservoir': 'BUH',
    'burley gate': 'BUG',
    bude: 'BUD',
    buckingham: 'BUC',
    burbage: 'BUB',
    buttermere: 'BTT',
    ballater: 'BTR',
    bridlington: 'BTN',
    battle: 'BTL',
    'bassenthwaite lake nw': 'BTH',
    'bassenthwaite e': 'BT2',
    'brecon sw': 'BSW',
    'bunessan pier': 'BSS',
    'basingstoke n': 'BSN',
    'bury st edmunds': 'BSE',
    'bury st edmunds n': 'BS2',
    'bury st edmunds s': 'BS1',
    bromyard: 'BRY',
    barrow: 'BRW',
    bruton: 'BRU',
    'brent tor': 'BRT',
    'braemar stadium': 'BRS',
    brora: 'BRR',
    brampton: 'BRP',
    broadway: 'BRO',
    burn: 'BRN',
    bromsgrove: 'BRM',
    brill: 'BRL',
    'broad oak': 'BRK',
    bridgnorth: 'BRI',
    brough: 'BRH',
    brenig: 'BRG',
    'bradford-on-avon': 'BRF',
    brecon: 'BRE',
    bradbury: 'BRD',
    'brackley south': 'BRC',
    bridport: 'BPT',
    barnstaple: 'BPL',
    bozeat: 'BOZ',
    'bourton-on-the-water': 'BOW',
    'bovey tracey': 'BOV',
    bourne: 'BOU',
    bottesford: 'BOT',
    boston: 'BOS',
    boroughbridge: 'BOR',
    'booker airfield': 'BOO',
    boncath: 'BON',
    'bodmin sw': 'BOM',
    bootle: 'BOL',
    'bridge of gaur': 'BOG',
    bodiam: 'BOD',
    'bridge of cally': 'BOC',
    'booker m40 bridge': 'BOB',
    'bridge of avon': 'BOA',
    'rockwell end': 'BO5',
    'turville windmill': 'BO4',
    'booker nw': 'BO3',
    'booker w': 'BO2',
    'booker sw': 'BO1',
    'bicester north west': 'BNW',
    'ben nevis': 'BNV',
    brinkworth: 'BNK',
    bingham: 'BNG',
    'braemar east': 'BMR',
    brynamman: 'BMM',
    balmaha: 'BMA',
    bletchley: 'BLY',
    'barnsley w': 'BLW',
    'barnsley s': 'BLS',
    'blair atholl': 'BLR',
    'bolsover sw': 'BLO',
    blanchland: 'BLN',
    'blakeney point': 'BLK',
    blidworth: 'BLI',
    balloch: 'BLH',
    ballinluig: 'BLG',
    'blaenau ffestiniog': 'BLF',
    'blenheim n': 'BLE',
    blandford: 'BLD',
    'blakehill farm': 'BLA',
    'brinkley church': 'BKY',
    'bishop auckland': 'BIS',
    birdlip: 'BIR',
    biddenden: 'BIN',
    billinghay: 'BIL',
    biggleswade: 'BIG',
    'broughton-in-furness': 'BIF',
    'bicester east': 'BIE',
    bidford: 'BID',
    'bicester control tower': 'BIC',
    'bicester rail bridge': 'BIB',
    'bath north': 'BHN',
    'basingstoke west': 'BGW',
    'bedlands gate': 'BGT',
    blairgowrie: 'BGR',
    'bangor se': 'BGO',
    brigg: 'BGG',
    biggar: 'BGA',
    banff: 'BFF',
    'booker finish nw': 'BF2',
    'booker finish sw': 'BF1',
    'bewl water': 'BEW',
    beverley: 'BEV',
    beulah: 'BEU',
    beattock: 'BET',
    'st bees head': 'BES',
    'berwick w': 'BER',
    bentpath: 'BEN',
    bembridge: 'BEM',
    bellingham: 'BEL',
    'beer head w': 'BEE',
    'bedford bridge': 'BED',
    beaminster: 'BEA',
    bardney: 'BDY',
    bodelwyddan: 'BDW',
    balado: 'BDO',
    'beadnell harbour': 'BDN',
    'bodmin se': 'BDM',
    'bidford finish w': 'BD2',
    'bidford finish e': 'BD1',
    banchory: 'BCY',
    'bishops cleeve w': 'BCW',
    'bishops castle': 'BCS',
    brechin: 'BCN',
    'bishop\'s cleeve nw': 'BCL',
    'banchory east': 'BCE',
    'bishop\'s caundle': 'BCA',
    'bicester n': 'BC3',
    'bicester ne': 'BC2',
    'bicester airfield': 'BC1',
    'bath bridge': 'BBR',
    'bracken bank': 'BBK',
    'banchory west': 'BAW',
    'bath racecourse sw': 'BAT',
    basingstoke: 'BAS',
    'barnard castle': 'BAR',
    banbury: 'BAN',
    bampton: 'BAM',
    bala: 'BAL',
    bakewell: 'BAK',
    barrhill: 'BAH',
    'bangor-on-dee': 'BAG',
    balfron: 'BAF',
    'bath east': 'BAE',
    badminton: 'BAD',
    'backwater reservoir': 'BAC',
    'ballachulish bridge': 'BAB',
    'banbury n': 'BA2',
    'banbury w': 'BA1',
    aysgarth: 'AYS',
    aylesbury: 'AYL',
    axminster: 'AXM',
    avebury: 'AVE',
    auldgirth: 'AUL',
    'alton towers': 'ATW',
    attleborough: 'ATT',
    atherstone: 'ATH',
    ashley: 'ASY',
    'airdrie southwest': 'ASW',
    'aston down': 'AST',
    'ashford south': 'ASS',
    aspatria: 'ASP',
    ashbourne: 'ASH',
    'ashford east': 'ASE',
    ashbury: 'ASB',
    arundel: 'ARU',
    'ardrishaig lighthouse': 'ARL',
    ardvasar: 'ARD',
    appleby: 'APP',
    'ansty cross': 'ANX',
    'andover se': 'ANE',
    'andover sw': 'AND',
    amulree: 'AMU',
    ambleside: 'AMS',
    amberley: 'AMB',
    alyth: 'ALY',
    'alton southwest': 'ALW',
    alva: 'ALV',
    alton: 'ALT',
    'alfreton south': 'ALS',
    alston: 'ALO',
    'alnwick moor sw': 'ALM',
    'allendale bridge': 'ALL',
    alfreton: 'ALF',
    aylesham: 'ALE',
    alcester: 'ALC',
    'aln bridge': 'ALB',
    altnaharra: 'AHA',
    'abergele south': 'AGS',
    alford: 'AFD',
    'alfriston bridge': 'AFB',
    andoversford: 'ADF',
    'aberdare se': 'ADE',
    achnabourin: 'ACN',
    achnasheen: 'ACH',
    'accrington ne': 'ACC',
    'aberystwyth pier': 'ABY',
    'abergavenny sw': 'ABS',
    aberchirder: 'ABR',
    aboyne: 'ABO',
    'abingdon bridge': 'ABN',
    aberfoyle: 'ABL',
    abington: 'ABI',
    aberfeldy: 'ABF',
    abergavenny: 'ABE',
    'aboyne dinnet': 'ABD',
    'abbot\'s bromley': 'ABB'
};

export default turnpoints;
