scss_files: 'assets/sass/**/*.scss'

linters:
  BorderZero:
    enabled: false

  Indentation:
    severity: warning
    width: 4

  ImportantRule:
    enabled: false

  IdSelector:
    enabled: false
